import postgres from 'postgres'
import { PIPELINE_STAGES } from '../../lib/pipeline'

export type BusinessRow = { id: string; name: string; slug: string; industry: string | null; websiteUrl: string | null; city: string | null; state: string | null; status: string; opportunityScore: number | null }
type Database = ReturnType<typeof postgres>
function sqlClient(): Database | null { const url = process.env.DATABASE_URL; return url ? postgres(url, { prepare: false, max: 1 }) : null }
export async function withDb<T>(work: (sql: Database) => Promise<T>, fallback: T): Promise<T> { const sql = sqlClient(); if (!sql) return fallback; try { return await work(sql) } catch { return fallback } finally { await sql.end({ timeout: 2 }).catch(() => undefined) } }
export async function getBusinesses(limit = 100, filters: { q?: string; stage?: string } = {}): Promise<BusinessRow[]> {
  const q = (filters.q ?? '').trim()
  const stage = (filters.stage ?? '').trim()
  const like = `%${q.replace(/[%_]/g, m => '\\' + m)}%`
  return withDb<BusinessRow[]>(sql => sql<BusinessRow[]>`
    select id,name,slug,industry,website_url as "websiteUrl",city,state,status,opportunity_score as "opportunityScore"
    from businesses
    where (${q === ''} or name ilike ${like} or coalesce(industry,'') ilike ${like}
           or coalesce(city,'') ilike ${like} or coalesce(state,'') ilike ${like} or coalesce(email,'') ilike ${like})
      and (${stage === ''} or status = ${stage})
    order by updated_at desc limit ${limit}`, [])
}
export async function getBusiness(slug: string) { return withDb(async sql => { const [business] = await sql<any[]>`select id,name,slug,legal_name as "legalName",industry,website_url as "websiteUrl",phone,email,address,city,state,postal_code as "postalCode",country,status,opportunity_score as "opportunityScore",notes,created_at as "createdAt",updated_at as "updatedAt" from businesses where slug=${slug} limit 1`; if (!business) return null; const [audit] = await sql<any[]>`select overall_score as "overallScore",design_score as "designScore",mobile_score as "mobileScore",performance_score as "performanceScore",seo_score as "seoScore",accessibility_score as "accessibilityScore",conversion_score as "conversionScore",findings,created_at as "createdAt" from website_audits where business_id=${business.id} order by created_at desc limit 1`; const contacts=await sql<any[]>`select id,name,role,email,phone,source from business_contacts where business_id=${business.id} order by created_at desc`; const activities=await sql<any[]>`select id,type,title,detail,created_at as "createdAt" from business_activities where business_id=${business.id} order by created_at desc limit 50`; const [opportunity]=await sql<any[]>`select id,name,stage,value_cents as "valueCents",probability,lost_reason as "lostReason" from opportunities where business_id=${business.id} order by updated_at desc limit 1`; const demos=await sql<any[]>`select id,slug,status,created_at as "createdAt" from demos where business_id=${business.id} order by created_at desc`; return { business,audit,contacts,activities,opportunity,demos } }, null) }
export async function getCounts(){return withDb(async sql=>{const [r]=await sql<any[]>`select (select count(*)::int from businesses) as businesses,(select count(*)::int from opportunities where stage not in ('won','lost')) as opportunities,(select count(*)::int from demos where status in ('ready','approved')) as demos_ready,(select count(*)::int from clients) as clients,(select count(*)::int from projects where status not in ('complete','cancelled')) as active_projects,(select count(*)::int from production_websites) as websites,(select count(*)::int from production_websites where hosting_mode is not null) as hosted_websites,(select count(*)::int from business_activities where type='inbound_contact') as inquiries`; return r??{businesses:0,opportunities:0,demos_ready:0,clients:0,active_projects:0,websites:0,hosted_websites:0,inquiries:0}}, {businesses:0,opportunities:0,demos_ready:0,clients:0,active_projects:0,websites:0,hosted_websites:0,inquiries:0})}
export async function getPipeline(){return withDb<any[]>(async sql=>{const rows=await sql<any[]>`select o.id as "opportunityId",o.stage,o.value_cents as "valueCents",b.name,b.slug,b.opportunity_score as score from opportunities o join businesses b on b.id=o.business_id where o.stage <> 'lost' order by array_position(${[...PIPELINE_STAGES]}::text[],o.stage),b.updated_at desc`; const grouped=new Map<string,any>(); for(const row of rows){if(!grouped.has(row.stage)) grouped.set(row.stage,{stage:row.stage,count:0,businesses:[]}); const group=grouped.get(row.stage); group.count++; group.businesses.push({opportunityId:row.opportunityId,name:row.name,slug:row.slug,score:row.score,valueCents:row.valueCents})} return [...grouped.values()]}, [])}
export async function getDemos(){return withDb<any[]>(sql=>sql<any[]>`select d.id,d.slug,d.status,d.preview_url as "previewUrl",d.created_at as "createdAt",d.approved_at as "approvedAt",b.name,b.slug as "businessSlug",b.opportunity_score as score from demos d join businesses b on b.id=d.business_id order by d.created_at desc limit 100`,[])}
export async function getOutreach(){return withDb<any[]>(sql=>sql<any[]>`select a.id,a.type,a.title,a.detail,a.created_at as "createdAt",b.name,b.slug from business_activities a join businesses b on b.id=a.business_id where a.type in ('outreach','email','follow_up','proposal') or a.title ilike '%email%' or a.title ilike '%outreach%' order by a.created_at desc limit 100`,[])}
export async function getInquiries(limit = 100){return withDb<any[]>(sql=>sql<any[]>`select a.id,a.detail,a.metadata,a.created_at as "createdAt",b.id as "businessId",b.name as business,b.slug,b.email as "businessEmail",b.phone as "businessPhone",b.website_url as "websiteUrl",o.stage,o.id as "opportunityId" from business_activities a join businesses b on b.id=a.business_id left join opportunities o on o.id=a.opportunity_id where a.type='inbound_contact' order by a.created_at desc limit ${limit}`,[])}
export async function getContacts(limit = 250){return withDb<any[]>(sql=>sql<any[]>`select c.id,c.name,c.role,c.email,c.phone,c.source,c.created_at as "createdAt",b.name as business,b.slug,b.city,b.state,b.status as "businessStatus" from business_contacts c join businesses b on b.id=c.business_id order by c.created_at desc limit ${limit}`,[])}
export async function getProposals(limit = 250){return withDb<any[]>(sql=>sql<any[]>`select o.id,o.name,o.stage,o.value_cents as "valueCents",o.probability,o.updated_at as "updatedAt",o.lost_reason as "lostReason",b.name as business,b.slug from opportunities o join businesses b on b.id=o.business_id where o.stage in ('proposal','won','lost') order by case o.stage when 'proposal' then 0 when 'won' then 1 else 2 end,o.updated_at desc limit ${limit}`,[])}
export async function getDemoBySlug(slug: string){return withDb<any|null>(async sql=>{const [row]=await sql<any[]>`select d.id,d.slug,d.status,d.metadata,d.approved_at as "approvedAt",b.name as business,b.slug as "businessSlug" from demos d join businesses b on b.id=d.business_id where d.slug=${slug} limit 1`; if(!row)return null; return {...row, content: row.metadata?.content ?? null}}, null)}
export async function getClients(){return withDb<any[]>(sql=>sql<any[]>`select c.id,c.status,c.hosting_mode as "hostingMode",b.name,b.slug,b.industry,(select count(*)::int from projects p where p.client_id=c.id) as projects,(select count(*)::int from production_websites w where w.business_id=b.id) as websites from clients c join businesses b on b.id=c.business_id order by c.updated_at desc limit 100`,[])}
export async function getProjects(){return withDb<any[]>(sql=>sql<any[]>`select p.id,p.name,p.status,p.created_at as "createdAt",b.name as business,b.slug,c.status as "clientStatus" from projects p join businesses b on b.id=p.business_id left join clients c on c.id=p.client_id order by p.updated_at desc limit 100`,[])}
export async function getWebsites(){return withDb<any[]>(sql=>sql<any[]>`select w.id,w.domain,w.status,w.hosting_mode as "hostingMode",w.deployment_url as "deploymentUrl",w.repository_url as "repositoryUrl",b.name as business,b.slug from production_websites w join businesses b on b.id=w.business_id order by w.updated_at desc limit 100`,[])}
export async function getAnalytics(){return withDb(async sql=>{const [r]=await sql<any[]>`select (select count(*)::int from businesses) as leads,(select count(*)::int from opportunities where stage='qualified') as qualified,(select count(*)::int from demos) as demos,(select count(*)::int from clients) as clients,(select count(*)::int from projects) as projects,(select count(*)::int from production_websites) as websites`; return r??{leads:0,qualified:0,demos:0,clients:0,projects:0,websites:0}}, {leads:0,qualified:0,demos:0,clients:0,projects:0,websites:0})}
