import ContactForm from './ContactForm'
import { RcvMark } from './admin/RcvMark'

const features=[['01','Find the opportunity','We identify local service businesses where a better digital presence can directly improve trust, calls, and conversions.'],['02','Build the concept','We research the business and create a tailored demo using its real services, positioning, and local market.'],['03','Send the proposal','The business receives a polished, personalized preview instead of another generic agency pitch.'],['04','Build the real thing','When they say yes, the concept becomes a production-ready website built around the actual business.']];
const benefits=[['Built around your business','Real information, real services, real customers — never a generic template.'],['Designed to convert','Clear messaging, strong calls to action, mobile-first UX, and a modern visual system.'],['No hosting lock-in','Keep it hosted with RCV Agency for a simple recurring fee or take the complete code with you.']];
export default function Home(){return <main className="site"><header className="siteNav"><div className="navInner"><a className="siteLogo" href="/"><RcvMark size={30}/><b>RCV <span>AGENCY</span></b></a><nav className="navLinks"><a href="#work">What we build</a><a href="#process">Process</a><a href="#hosting">Hosting</a></nav><a className="navCta" href="#contact">Start a project <span>↗</span></a></div></header>
<section className="hero"><div className="heroGlow one"/><div className="heroGlow two"/><div className="container heroGrid"><div className="heroCopy"><div className="eyebrow"><i/> Websites for ambitious local businesses</div><h1>A better website.<br/><span>A better business.</span></h1><p>RCV Agency creates modern websites for local service businesses that want to look as good online as they do in person.</p><div className="heroActions"><a className="button dark" href="#demo">See a concept <span>→</span></a><a className="textLink" href="#process">How it works <span>↓</span></a></div><div className="heroProof"><span><b>01</b> Research</span><span><b>02</b> Concept</span><span><b>03</b> Build</span></div></div><div className="heroVisual"><div className="browser floating"><div className="browserTop"><div><i/><i/><i/></div><span>harrisonandsons.com</span><b>↗</b></div><div className="mockHero"><div className="mockBadge">INDIANAPOLIS · HVAC & PLUMBING</div><div className="mockNav"><strong>HARRISON<span>+</span>SONS</strong><span>Services</span><span>About</span><span>Reviews</span><button>Call now</button></div><div className="mockSplit"><div><div className="mockKicker">LOCAL SERVICE. DONE RIGHT.</div><h2>Comfort at home.<br/><em>Service you can trust.</em></h2><p>Expert heating, cooling & plumbing for Indianapolis homes.</p><div><button className="mockPrimary">Request service <span>→</span></button><button className="mockSecondary">View services</button></div></div><div className="mockPhoto"><div className="photoGlow"/><div className="houseIcon">⌂</div><span>15+ YEARS<br/>LOCAL EXPERTISE</span></div></div><div className="mockStats"><div><b>4.9<span>★</span></b><span>Google rating</span></div><div><b>5,000+</b><span>Homes served</span></div><div><b>24/7</b><span>Emergency service</span></div></div></div></div></div></div></section>
<section className="trust"><div className="container trustInner"><span>THE RCV APPROACH</span><div><b>Real business.</b><b>Real research.</b><b>Real website.</b></div></div></section>
<section id="demo" className="section concept"><div className="container"><div className="sectionIntro"><div><div className="eyebrow"><i/> The concept</div><h2>Don't imagine<br/>your new site.<br/><span>See it.</span></h2></div><p>Before you commit to anything, we can create a tailored concept around your actual business — your services, your market, your story, and the customers you want to reach.</p></div><div className="largeDemo"><div className="browserTop"><div><i/><i/><i/></div><span>harrisonandsons.com</span><b>↗</b></div><div className="demoBody"><div className="demoNav"><strong>HARRISON<span>+</span>SONS</strong><div><span>Services</span><span>About</span><span>Reviews</span><span>Contact</span></div><button>Schedule service</button></div><div className="demoHero"><div className="demoHeroCopy"><small>INDIANAPOLIS · SERVING MARION COUNTY</small><h3>Your home.<br/><em>In good hands.</em></h3><p>Heating, cooling and plumbing backed by local people who care.</p><div className="demoButtons"><button>Schedule service <span>→</span></button><span>★ 4.9 · 327 reviews</span></div></div><div className="demoImage"><div className="sun"/><div className="house"/><div className="demoImageTag">LOCALLY OWNED<br/><b>EST. 2009</b></div></div></div><div className="demoServices"><div><span>01</span><b>Heating</b><small>Comfort all winter.</small></div><div><span>02</span><b>Cooling</b><small>Stay comfortable.</small></div><div><span>03</span><b>Plumbing</b><small>We fix the problem.</small></div><div><span>04</span><b>Maintenance</b><small>Prevent the surprise.</small></div></div></div></div></div></section>
<section id="work" className="section build"><div className="container"><div className="eyebrow"><i/> What we build</div><div className="buildHead"><h2>Websites that feel<br/><span>established.</span></h2><p>Not bloated. Not cookie-cutter. Just a thoughtful digital home that makes a local business feel credible, modern, and easy to choose.</p></div><div className="benefitGrid">{benefits.map(([title,text],i)=><article key={title}><span className={'benefitIcon i'+i}>{['✦','↗','◌'][i]}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section id="process" className="section process"><div className="container"><div className="eyebrow"><i/> How it works</div><h2>From first impression<br/><span>to finished website.</span></h2><div className="steps">{features.map(([n,title,text])=><article key={n}><b>{n}</b><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section id="hosting" className="section ownership"><div className="container ownershipGrid"><div><div className="eyebrow"><i/> Ownership</div><h2>Your website.<br/><span>Your choice.</span></h2></div><div><p>Host with RCV Agency for a simple recurring fee and let us keep everything running, or take the complete project and host it yourself.</p><div className="ownershipRows"><div><b>RCV Hosting</b><span>We manage the infrastructure, updates, and maintenance.</span></div><div><b>Self-hosted</b><span>We hand over the complete codebase. You choose where it runs.</span></div></div></div></div></section>
<section id="contact" className="cta"><div className="ctaGlow"/><div className="container"><div className="eyebrow"><i/> Start a project</div><h2>Tell us about your<br/><span>next website.</span></h2><p>If your business needs a stronger online presence, tell us what you have in mind. Your request goes directly into our AgencyOS workspace so we can follow up.</p><ContactForm/></div></section>
<footer className="footer"><div className="container"><a className="siteLogo" href="/"><RcvMark size={30}/><b>RCV <span>AGENCY</span></b></a><span>© 2026 RCV Agency</span><span>Built with intention.</span></div></footer></main>}
