import ContactForm from './ContactForm'
import { RcvMark } from './components/RcvMark'

const features=[['01','Find the opportunity','We identify local service businesses where a better digital presence can directly improve trust, calls, and conversions.'],['02','Build the concept','We research the business and create a tailored demo using its real services, positioning, and local market.'],['03','Send the proposal','The business receives a polished, personalized preview instead of another generic agency pitch.'],['04','Build the real thing','When they say yes, the concept becomes a production-ready website built around the actual business.']];
const benefits=[['Built around your business','Real information, real services, real customers — never a generic template.'],['Designed to convert','Clear messaging, strong calls to action, mobile-first UX, and a modern visual system.'],['No hosting lock-in','Keep it hosted with RCV Agency for a simple recurring fee or take the complete code with you.']];
const services=[['layer-group','Website design & build','A complete site built around your services, your market, and the customers you actually want to reach.'],['mobile-android','Mobile-first development','Most local searches happen on a phone. The site is designed for that first, then scaled up to desktop.'],['comment-alt-lines','Conversion & enquiry paths','Clear calls to action, tap-to-call, and forms that put real enquiries in front of you instead of into a void.'],['search-alt','Local SEO foundations','Clean structure, fast pages, correct metadata, and the local signals search engines actually look for.'],['palette','Brand & visual identity','Type, colour, and imagery that make a small operation look as established as it really is.'],['server-network','Hosting & maintenance','Optional. We keep it online, updated, and backed up — or hand you everything and step out of the way.']];
const reasons=[['01','We start with your business, not a template','Before anything is designed we look at what you do, who you serve, and what your market already looks like online.'],['02','Designed to convert, not to win awards','A local business site has one job: turn a visitor into a call, a booking, or a form. Every decision serves that.'],['03','You talk to the person building it','No account managers relaying messages. The person who understands the project is the person doing the work.'],['04','No lock-in, in either direction','Host with us or take the entire codebase and run it yourself. Both are real options, chosen by you.'],['05','Built on modern foundations','Fast, secure, accessible, and maintainable — so the site is still an asset in three years, not a liability.']];
const faqs=[['How much does a website cost?','It depends on scope. A five-page site for a single-location business is a very different build from a multi-service site with online booking. We look at what you actually need, then quote a fixed price before any work begins — no hourly billing and no surprises later.'],['How long does it take?','Most local business sites take a few weeks from kickoff to launch. The largest variable is usually how quickly we can get content, photos, and feedback back from you, so we tell you exactly what we need at the start.'],['Do I have to host with RCV Agency?','No. You can host with us for a recurring fee and we handle updates, backups, and uptime — or we hand over the complete source code and you host it wherever you like. Both are first-class options, not an upsell and a punishment.'],['Do I actually own the website?','Yes. If you choose the handover option you receive the complete codebase along with deployment instructions. Nothing is trapped inside a proprietary builder you cannot leave.'],['I already have a website. Can you work with it?','Usually we rebuild rather than patch. If a site is on an ageing platform or was never built for mobile, starting fresh is normally faster and cheaper than retrofitting it. And if we think your current site is genuinely fine as it is, we will tell you that.'],['What do you need from me?','Your services, your service area, how you want people to get in touch, and any photos or brand assets you already have. If you do not have photography, we will talk through the options — we will not quietly fill your site with stock images of strangers.'],['What if I am not sure what I need?','That is a perfectly normal place to start. Describe the business in the form below and we will come back with a straight recommendation — including telling you if we think you do not need us yet.']];
export default function Home(){return <main className="site"><header className="siteNav"><div className="navInner"><a className="siteLogo" href="/"><RcvMark size={30}/><b>RCV <span>AGENCY</span></b></a><nav className="navLinks"><a href="#before-after">Before &amp; after</a><a href="#services">Services</a><a href="#process">Process</a><a href="#why">Why us</a><a href="#faq">FAQ</a></nav><a className="navCta" href="#contact">Start a project <span>↗</span></a></div></header>
<section className="hero"><div className="heroGlow one"/><div className="heroGlow two"/><div className="container heroGrid"><div className="heroCopy"><div className="eyebrow"><i/> Websites for ambitious local businesses</div><h1>A better website.<br/><span>A better business.</span></h1><p>RCV Agency creates modern websites for local service businesses that want to look as good online as they do in person.</p><div className="heroActions"><a className="button dark" href="#demo">See a concept <span>→</span></a><a className="textLink" href="#process">How it works <span>↓</span></a></div><div className="heroProof"><span><b>01</b> Research</span><span><b>02</b> Concept</span><span><b>03</b> Build</span></div></div><div className="heroVisual"><div className="browser floating"><div className="browserTop"><div><i/><i/><i/></div><span>harrisonandsons.com</span><b>↗</b></div><div className="mockHero"><div className="mockBadge">INDIANAPOLIS · HVAC & PLUMBING</div><div className="mockNav"><strong>HARRISON<span>+</span>SONS</strong><span>Services</span><span>About</span><span>Reviews</span><button>Call now</button></div><div className="mockSplit"><div><div className="mockKicker">LOCAL SERVICE. DONE RIGHT.</div><h2>Comfort at home.<br/><em>Service you can trust.</em></h2><p>Expert heating, cooling & plumbing for Indianapolis homes.</p><div><button className="mockPrimary">Request service <span>→</span></button><button className="mockSecondary">View services</button></div></div><div className="mockPhoto"><div className="photoGlow"/><div className="houseIcon">⌂</div><span>15+ YEARS<br/>LOCAL EXPERTISE</span></div></div><div className="mockStats"><div><b>4.9<span>★</span></b><span>Google rating</span></div><div><b>5,000+</b><span>Homes served</span></div><div><b>24/7</b><span>Emergency service</span></div></div></div></div></div></div></section>
<section className="trust"><div className="container trustInner"><span>THE RCV APPROACH</span><div><b>Real business.</b><b>Real research.</b><b>Real website.</b></div></div></section>
<section id="demo" className="section concept"><div className="container"><div className="sectionIntro"><div><div className="eyebrow"><i/> The concept</div><h2>Don't imagine<br/>your new site.<br/><span>See it.</span></h2></div><p>Before you commit to anything, we can create a tailored concept around your actual business — your services, your market, your story, and the customers you want to reach.</p></div><div className="largeDemo"><div className="browserTop"><div><i/><i/><i/></div><span>harrisonandsons.com</span><b>↗</b></div><div className="demoBody"><div className="demoNav"><strong>HARRISON<span>+</span>SONS</strong><div><span>Services</span><span>About</span><span>Reviews</span><span>Contact</span></div><button>Schedule service</button></div><div className="demoHero"><div className="demoHeroCopy"><small>INDIANAPOLIS · SERVING MARION COUNTY</small><h3>Your home.<br/><em>In good hands.</em></h3><p>Heating, cooling and plumbing backed by local people who care.</p><div className="demoButtons"><button>Schedule service <span>→</span></button><span>★ 4.9 · 327 reviews</span></div></div><div className="demoImage"><div className="sun"/><div className="house"/><div className="demoImageTag">LOCALLY OWNED<br/><b>EST. 2009</b></div></div></div><div className="demoServices"><div><span>01</span><b>Heating</b><small>Comfort all winter.</small></div><div><span>02</span><b>Cooling</b><small>Stay comfortable.</small></div><div><span>03</span><b>Plumbing</b><small>We fix the problem.</small></div><div><span>04</span><b>Maintenance</b><small>Prevent the surprise.</small></div></div></div></div><p className="demoNote"><i className="uil uil-info-circle"/> Example concept built for a fictional business, to show the level of finish.</p></div></section>
<section id="before-after" className="section beforeAfter"><div className="container"><div className="sectionIntro"><div><div className="eyebrow"><i/> Before &amp; after</div><h2>The difference<br/>isn&apos;t subtle.</h2></div><p>Most local service businesses aren&apos;t losing to great websites. They&apos;re losing to sites like the one on the left — and a better one changes how the business is judged before anyone picks up the phone.</p></div>
<div className="baGrid">
<figure className="baPanel"><figcaption className="baLabel"><span className="baTag before">Before</span> A typical ageing local site</figcaption>
<div className="baFrame"><div className="baChrome"><div><i/><i/><i/></div><span>example-plumbing.com</span></div>
<div className="baOld"><div className="baOldHead"><b>EXAMPLE PLUMBING &amp; HEATING CO.</b><span>Serving the area since 1998</span></div><div className="baOldNav"><a>Home</a>|<a>Services</a>|<a>About Us</a>|<a>Contact</a></div><h4>Welcome to Our Website!</h4><p>We are a family owned plumbing and heating company offering a wide range of services to residential and commercial customers throughout the greater metro area at competitive rates.</p><div className="baOldBody"><div className="baOldPhoto">[ photo ]</div><ul><li>Plumbing Repairs</li><li>Water Heaters</li><li>Drain Cleaning</li><li>Heating &amp; Cooling</li></ul></div><p className="baOldFoot">Call us today: (555) 010-2938 &nbsp;·&nbsp; Email: info@exampleplumbing.com<br/><small>Last updated: March 2011</small></p></div></div>
<ul className="baPoints bad"><li>Unreadable on a phone</li><li>No clear next step</li><li>Nothing that builds trust</li><li>Looks abandoned</li></ul></figure>

<figure className="baPanel"><figcaption className="baLabel"><span className="baTag after">After</span> The same business, rebuilt</figcaption>
<div className="baFrame lifted"><div className="baChrome"><div><i/><i/><i/></div><span>exampleplumbing.com</span></div>
<div className="baNew"><div className="baNewNav"><strong>EXAMPLE<span>·</span>PLUMBING</strong><em>Services</em><em>Areas</em><em>Reviews</em><button>Call now</button></div><div className="baNewHero"><div><small>LICENSED &amp; INSURED · 24/7 EMERGENCY</small><h4>Heating and plumbing,<br/>done properly.</h4><p>Same-day callouts across the metro area.</p><div className="baNewCta"><button>Book a visit →</button><span>★★★★★ <b>4.9</b></span></div></div><div className="baNewArt"><i className="baSun"/><i className="baRoof"/></div></div><div className="baNewRow"><div><b>Repairs</b><small>Fast diagnosis</small></div><div><b>Water heaters</b><small>Repair or replace</small></div><div><b>Drains</b><small>Cleared same day</small></div></div></div></div>
<ul className="baPoints good"><li>Built mobile-first</li><li>One obvious action</li><li>Credentials up front</li><li>Looks current and staffed</li></ul></figure>
</div>
<p className="baNote"><i className="uil uil-info-circle"/> Illustrative concept using a fictional business — not a real client site.</p>
</div></section>
<section id="work" className="section build"><div className="container"><div className="eyebrow"><i/> What we build</div><div className="buildHead"><h2>Websites that feel<br/><span>established.</span></h2><p>Not bloated. Not cookie-cutter. Just a thoughtful digital home that makes a local business feel credible, modern, and easy to choose.</p></div><div className="benefitGrid">{benefits.map(([title,text],i)=><article key={title}><span className={'benefitIcon i'+i}>{['✦','↗','◌'][i]}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section id="services" className="section services"><div className="container"><div className="sectionIntro"><div><div className="eyebrow"><i/> Services</div><h2>Everything the site<br/><span>needs to work.</span></h2></div><p>Not a menu of add-ons. These are the parts that have to be right together for a local business website to actually bring in work.</p></div>
<div className="svcGrid">{services.map(([icon,title,text],i)=><article key={title}><span className={'svcIcon s'+(i%3)}><i className={'uil uil-'+icon}/></span><h3>{title}</h3><p>{text}</p></article>)}</div>
</div></section>
<section id="process" className="section process"><div className="container"><div className="eyebrow"><i/> How it works</div><h2>From first impression<br/><span>to finished website.</span></h2><div className="steps">{features.map(([n,title,text])=><article key={n}><b>{n}</b><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section id="why" className="why"><div className="whyGlow one"/><div className="whyGlow two"/><div className="container whyInner"><div className="whyHead"><div className="eyebrow dark"><i/> Why RCV Agency</div><h2>A small agency<br/><span>that acts like one.</span></h2><p>No layers, no handoffs, and no template with your logo dropped into it. Here is what that means in practice.</p></div>
<ol className="whyList">{reasons.map(([n,title,text])=><li key={n}><b>{n}</b><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol>
</div></section>
<section id="hosting" className="section ownership"><div className="container ownershipGrid"><div><div className="eyebrow"><i/> Ownership</div><h2>Your website.<br/><span>Your choice.</span></h2></div><div><p>Host with RCV Agency for a simple recurring fee and let us keep everything running, or take the complete project and host it yourself.</p><div className="ownershipRows"><div><b>RCV Hosting</b><span>We manage the infrastructure, updates, and maintenance.</span></div><div><b>Self-hosted</b><span>We hand over the complete codebase. You choose where it runs.</span></div></div></div></div></section>
<section id="faq" className="section faq"><div className="container"><div className="sectionIntro"><div><div className="eyebrow"><i/> Questions</div><h2>The things<br/><span>people ask.</span></h2></div><p>Straight answers. If something you need to know isn&apos;t here, ask in the form below and we&apos;ll answer it properly.</p></div>
<div className="faqList">{faqs.map(([q,a],i)=><details key={q} name="faq" open={i===0}><summary><span>{q}</span><i className="uil uil-plus"/></summary><p>{a}</p></details>)}</div>
</div></section>
<section id="contact" className="cta"><div className="ctaGlow"/><div className="container"><div className="eyebrow"><i/> Start a project</div><h2>Tell us about your<br/><span>next website.</span></h2><p>If your business needs a stronger online presence, tell us what you have in mind. Your request goes directly into our AgencyOS workspace so we can follow up.</p><ContactForm/></div></section>
<footer className="footer"><div className="container"><a className="siteLogo" href="/"><RcvMark size={30}/><b>RCV <span>AGENCY</span></b></a><span>© 2026 RCV Agency</span><span>Built with intention.</span></div></footer></main>}
