const data: Record<string, {name:string; location:string; industry:string; status:string; score:number; website:string; summary:string}> = {
  "harrison-sons-hvac": { name:"Harrison & Sons HVAC", location:"Indianapolis, IN", industry:"HVAC", status:"Demo Ready", score:91, website:"harrisonsons.com", summary:"Established local HVAC company with strong reputation and an outdated web presence. High potential for a conversion-focused redesign." },
  "summit-roofing-co": { name:"Summit Roofing Co.", location:"Fishers, IN", industry:"Roofing", status:"Researching", score:84, website:"summitroofingco.com", summary:"Local roofing prospect currently in research. The opportunity is driven by weak mobile presentation and unclear calls to action." },
  "blue-oak-landscaping": { name:"Blue Oak Landscaping", location:"Carmel, IN", industry:"Landscaping", status:"Contacted", score:78, website:"blueoaklandscaping.com", summary:"Promising landscaping business with an existing site that could better communicate services, proof and service area." },
  "precision-auto-care": { name:"Precision Auto Care", location:"Greenwood, IN", industry:"Auto Repair", status:"Interested", score:88, website:"precisionautocare.com", summary:"Interested prospect. Strong reviews and local demand make this a high-priority sales opportunity." },
  "evergreen-plumbing": { name:"Evergreen Plumbing", location:"Noblesville, IN", industry:"Plumbing", status:"Discovered", score:73, website:"evergreenplumbing.com", summary:"Newly discovered plumbing prospect awaiting qualification and website audit." },
};

export default async function BusinessProfile({ params }: { params: Promise<{slug:string}> }) {
  const { slug } = await params;
  const business = data[slug] ?? data["harrison-sons-hvac"];
  const activity = ["Business record created", "Initial website research completed", "Opportunity score calculated", business.status === "Demo Ready" ? "Website concept generated" : "Next research step queued"];
  return <div className="shell"><aside className="side"><div className="brand">RCV Agency</div><nav className="nav"><a href="/">Overview</a><a className="active" href="/businesses">Businesses</a><a href="/pipeline">Pipeline</a><a href="/demos">Demos</a><a href="/outreach">Outreach</a><a href="/clients">Clients</a><a href="/projects">Projects</a><a href="/websites">Websites</a><a href="/hosting">Hosting</a><a href="/ai">AI Operations</a><a href="/analytics">Analytics</a><a href="/settings">Settings</a></nav></aside><main className="main"><header className="top"><div><div className="kicker">Business Profile</div><h1 className="title">{business.name}</h1><div className="muted">{business.location} · {business.industry} · {business.website}</div></div><span className="pill">{business.status}</span></header><div className="grid"><div className="stat"><span>Opportunity score</span><b>{business.score}/100</b></div><div className="stat"><span>Pipeline stage</span><b style={{fontSize:20}}>{business.status}</b></div><div className="stat"><span>Website</span><b style={{fontSize:20}}>Auditing</b></div><div className="stat"><span>Relationship</span><b style={{fontSize:20}}>Prospect</b></div></div><section className="section"><h2>Business intelligence</h2><div className="panel" style={{padding:22}}><p className="muted" style={{lineHeight:1.7}}>{business.summary}</p><div className="grid" style={{marginTop:18}}><div className="stat"><span>Website</span><b style={{fontSize:16}}>{business.website}</b></div><div className="stat"><span>Industry</span><b style={{fontSize:16}}>{business.industry}</b></div><div className="stat"><span>Location</span><b style={{fontSize:16}}>{business.location}</b></div><div className="stat"><span>Next action</span><b style={{fontSize:16}}>Review</b></div></div></div></section><section className="section"><h2>Relationship timeline</h2><div className="panel">{activity.map((item,i)=><div className="row" key={item}><div><strong>{item}</strong><br/><small>{i === activity.length-1 ? "Current" : "Historical event"}</small></div><div><span className="pill">Activity</span></div><div><small>AgencyOS</small></div><div><small>Today</small></div></div>)}</div></section></main></div>;
}
