'use client'
import { useState } from 'react'
import { DISCOVERY_CATEGORIES } from '../../../lib/discovery'

export default function DiscoveryForm(){
 const [city,setCity]=useState(''); const [category,setCategory]=useState(''); const [radius,setRadius]=useState('25'); const [loading,setLoading]=useState(false); const [message,setMessage]=useState('')
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setMessage('');try{const r=await fetch('/api/admin/discovery',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({city,category,radius:Number(radius)})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Discovery failed');setMessage(`${data.place}: OpenStreetMap knows of ${data.found} ${category} ${data.found===1?'business':'businesses'} here — ${data.withoutWebsite} with no website. Added ${data.created} new record${data.created===1?'':'s'}${data.duplicates?`, skipped ${data.duplicates} already in your database`:''}.`)}catch(err){setMessage(err instanceof Error?err.message:'Discovery failed')}finally{setLoading(false)}}
 return <form onSubmit={submit} className="detail"><div className="split"><label className="field">City, state or postcode<input required value={city} onChange={e=>setCity(e.target.value)} placeholder="New Albany, Indiana" /></label><label className="field">Service category<select required value={category} onChange={e=>setCategory(e.target.value)}><option value="">Choose a category</option>{DISCOVERY_CATEGORIES.map(c=><option key={c} value={c}>{c.replace(/^./,x=>x.toUpperCase())}</option>)}</select></label></div><div className="actions" style={{marginTop:14}}><label className="field" style={{maxWidth:180}}>Radius (miles)<input type="number" min="1" max="100" value={radius} onChange={e=>setRadius(e.target.value)} /></label><button className="primary" disabled={loading}>{loading?'Searching…':'Find businesses'}</button></div>{message&&<div className="note" style={{marginTop:14}}>{message}</div>}<p className="muted" style={{marginTop:14,lineHeight:1.7}}>Searches OpenStreetMap, which is free and needs no account. Coverage is strongest in towns and cities and thinner for very small operators, so a low count means OpenStreetMap has little mapped here — not that no such businesses exist. Businesses with no website are listed first, because they are the strongest opportunities.</p></form>
}
